#!/bin/sh
# husky

# Created by Husky v4.3.0 (https://github.com/typicode/husky#readme)
#   At: 11/23/2020, 11:04:18 AM
#   From: /home/roxen/Artemis/node_modules/husky (https://github.com/typicode/husky#readme)

# Get push command
echo $(ps -ocommand= -p $PPID) > hooks/push.txt

# Husky
. "$(dirname "$0")/husky.sh"